// SECURITY:
// - All DB access goes through the Supabase JS client (PostgREST), which sends
//   values as JSON parameters — values are never interpolated into SQL strings,
//   so SQL injection is structurally not possible here.
// - `user_id` is taken from the Supabase session, never from form input.
// - `attendance_date` is generated by the app, not from the request body.
// - Row-Level Security policies on `public.attendance` enforce
//   `user_id = auth.uid()` for both SELECT and INSERT, so even a tampered
//   client cannot read or write another user's rows.
// - Duplicate check-ins are blocked by a UNIQUE (user_id, attendance_date)
//   constraint; the 23505 error is surfaced as a friendly message.
import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { CalendarCheck, Clock, ShieldCheck, CheckCircle2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export const Route = createFileRoute("/_student/attendance")({
  head: () => ({ meta: [{ title: "Mark Attendance — SecureAttend" }] }),
  component: AttendancePage,
});

function todayISO() {
  const d = new Date();
  return `${getDateTimePart(d, "year")}-${getDateTimePart(d, "month")}-${getDateTimePart(d, "day")}`;
}

const APP_TIME_ZONE = "Asia/Kuala_Lumpur";
const LATE_CUTOFF_HOUR = 9;

function getDateTimePart(date: Date, type: Intl.DateTimeFormatPartTypes) {
  const parts = new Intl.DateTimeFormat("en", {
    timeZone: APP_TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  }).formatToParts(date);

  return parts.find((part) => part.type === type)?.value;
}

function attendanceStatusFor(date = new Date()) {
  const hour = Number(getDateTimePart(date, "hour"));
  return hour >= LATE_CUTOFF_HOUR ? "late" : "present";
}

function formatTime(iso: string) {
  return new Date(iso).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

function AttendancePage() {
  const qc = useQueryClient();
  const [clientAuthReady, setClientAuthReady] = useState(false);
  const today = todayISO();

  useEffect(() => {
    setClientAuthReady(true);
  }, []);

  const {
    data: todayResult,
    isLoading,
    isError,
    error: todayError,
  } = useQuery({
    queryKey: ["attendance", "today", today],
    queryFn: async () => {
      const { data: sessionData, error: sessionErr } = await supabase.auth.getSession();
      if (sessionErr || !sessionData.session) {
        throw new Error(sessionErr?.message ?? "Your session expired. Please sign in again.");
      }

      const { data, error } = await supabase
        .from("attendance")
        .select("id, status, check_in_time, attendance_date")
        .eq("user_id", sessionData.session.user.id)
        .eq("attendance_date", today)
        .maybeSingle();

      if (error) throw new Error(error.message);
      return { record: data ?? null };
    },
    enabled: clientAuthReady,
  });

  const checkIn = useMutation({
    mutationFn: async () => {
      const { data: sessionData, error: sessionErr } = await supabase.auth.getSession();
      if (sessionErr || !sessionData.session) {
        throw new Error(sessionErr?.message ?? "Your session expired. Please sign in again.");
      }

      const { data, error } = await supabase
        .from("attendance")
        .insert({
          user_id: sessionData.session.user.id,
          attendance_date: today,
          check_in_time: new Date().toISOString(),
          status: attendanceStatusFor(),
        })
        .select("id, status, check_in_time, attendance_date")
        .single();

      if (error) {
        if (error.code === "23505") {
          const { data: existing, error: existingError } = await supabase
            .from("attendance")
            .select("id, status, check_in_time, attendance_date")
            .eq("user_id", sessionData.session.user.id)
            .eq("attendance_date", today)
            .maybeSingle();

          if (existingError) throw new Error(existingError.message);
          return { record: existing, alreadyCheckedIn: true };
        }

        throw new Error(error.message);
      }

      return { record: data, alreadyCheckedIn: false };
    },
    onSuccess: (result) => {
      toast.success(
        result.alreadyCheckedIn
          ? "You have already checked in today"
          : "Attendance recorded for today",
      );
      qc.invalidateQueries({ queryKey: ["attendance"] });
    },
    onError: (err: Error) => {
      toast.error(err.message || "Could not record attendance");
      qc.invalidateQueries({ queryKey: ["attendance", "today", today] });
    },
  });

  const todays = todayResult?.record ?? null;
  const alreadyCheckedIn = !!todays;
  const todayErrorMessage =
    todayError instanceof Error ? todayError.message : "Could not load today's attendance";

  return (
    <div className="mx-auto max-w-3xl space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold text-foreground sm:text-3xl">Mark attendance</h1>
        <p className="text-sm text-muted-foreground">
          You can check in once per day. Today is{" "}
          {new Date().toLocaleDateString(undefined, {
            weekday: "long",
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
          .
        </p>
      </div>

      <div
        className="rounded-xl border border-border bg-card p-6"
        style={{ boxShadow: "var(--shadow-card)" }}
      >
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
            <ShieldCheck className="h-5 w-5" />
          </div>
          <div>
            <div className="font-semibold text-foreground">Today's attendance</div>
            <div className="text-xs text-muted-foreground">
              Secured by your university-issued credentials.
            </div>
          </div>
        </div>

        <div className="mt-6 rounded-lg border border-border bg-muted/30 p-4">
          {!clientAuthReady || isLoading ? (
            <div className="flex items-center gap-3">
              <div className="h-9 w-9 rounded-lg skeleton-shimmer" />
              <div className="flex-1 space-y-2">
                <div className="h-3 w-40 rounded skeleton-shimmer" />
                <div className="h-3 w-24 rounded skeleton-shimmer" />
              </div>
            </div>
          ) : isError ? (
            <div className="text-sm text-destructive">{todayErrorMessage}</div>
          ) : alreadyCheckedIn ? (
            <div className="flex items-start gap-3 animate-scale-in">
              <CheckCircle2 className="mt-0.5 h-5 w-5 text-success" />
              <div className="flex-1">
                <div className="font-medium text-foreground">You're checked in for today</div>
                <div className="mt-1 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                  <span className="inline-flex items-center gap-1">
                    <CalendarCheck className="h-3.5 w-3.5" />
                    {todays!.attendance_date}
                  </span>
                  {todays!.check_in_time && (
                    <span className="inline-flex items-center gap-1">
                      <Clock className="h-3.5 w-3.5" />
                      {formatTime(todays!.check_in_time)}
                    </span>
                  )}
                  <span className="rounded-full bg-success/15 px-2 py-0.5 text-success capitalize">
                    {todays!.status}
                  </span>
                </div>
              </div>
            </div>
          ) : (
            <div className="text-sm text-muted-foreground">You haven't checked in yet today.</div>
          )}
        </div>

        <Button
          type="button"
          className="mt-6 w-full"
          size="lg"
          disabled={!clientAuthReady || isLoading || alreadyCheckedIn || checkIn.isPending}
          onClick={() => checkIn.mutate()}
        >
          {alreadyCheckedIn
            ? "Already checked in"
            : checkIn.isPending
              ? "Recording…"
              : "Check in now"}
        </Button>
      </div>

      <div className="rounded-xl border border-dashed border-border p-4 text-center text-xs text-muted-foreground">
        Duplicate check-ins are blocked at the database level — one record per student per day.
      </div>
    </div>
  );
}
